[package]
name = "rho-devshell"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
rho-fs-view.workspace = true
rho-watch.workspace = true
senax-encoder.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
rustix = { version = "1", features = ["process"] }
tokio = { workspace = true, features = ["net"] }

[dev-dependencies]
tempfile.workspace = true
