[package]
name = "rho-desktop-proto"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
senax = ["dep:senax-encoder", "dep:bytes"]
local = ["dep:tokio","dep:anyhow"]

[dependencies]
bytes = { version = "1", optional = true }
anyhow = {version="1",optional=true}
tokio = {version="1",features=["net","rt","io-util","time"],optional=true}
senax-encoder = { path = "../senax-encoder", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
