[package]
name = "rho-inference2"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
bytes = "1"
futures-util.workspace = true
rho-inference.workspace = true
rustls.workspace = true
senax-encoder.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }
tokio-tungstenite.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
