[package]
name = "rho-qa"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono = { version = "0.4", default-features = false, features = [
  "clock",
  "std",
] }
clap.workspace = true
base64.workspace = true
camino.workspace = true
dial9-trace-format = "0.4.1"
dirs.workspace = true
flate2 = "1"
redb.workspace = true
reqwest.workspace = true
rho-core.workspace = true
rho-fake-model.workspace = true
rho-ui-proto.workspace = true
rustls.workspace = true
rho-slack = { workspace = true, features = ["fake", "ui"] }
rho-gui = { path = "../rho-gui", features = ["walk-support"] }
serde = { workspace = true }
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tempfile.workspace = true

[dev-dependencies]
bytes.workspace = true
rho-db.workspace = true
senax-encoder.workspace = true
