[package]
edition.workspace = true
license.workspace = true
name = "rho-ui-proto"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
bytes.workspace = true
camino.workspace = true
chrono = { version = "0.4", default-features = false, features = ["std"] }
clock.workspace = true
futures.workspace = true
rho-core.workspace = true
rho-desk.workspace = true
rho-rpc.workspace = true
rho-shell-proto.workspace = true
rho-workspaces-types.workspace = true
senax-encoder.workspace = true
tokio = { version = "1", features = ["io-util"] }
text.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dirs.workspace = true
tokio = { version = "1", features = ["net"] }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tokio.workspace = true
