[package]
edition.workspace = true
license = "GPL-3.0-or-later"
name = "rho-zed-host"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
extension = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
fs = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
futures.workspace = true
gpui = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e", default-features = false }
gpui_platform = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e", default-features = false, features = [
  "font-kit",
] }
gpui_tokio = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
http_client = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
language = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
log = "0.4"
node_runtime = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
prost = "0.9"
release_channel = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
remote = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
remote_server = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
rpc = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
semver = { version = "1.0", features = ["serde"] }
settings = { git = "https://github.com/maan2003/zed", rev = "43e188b4229e" }
worktree.workspace = true
