// @generated by generate-gh.py; do not edit.
// GitHub REST OpenAPI commit 2b78fb0c53617f188e45979ecefd83b521c5428a; MIT
// license in github-openapi.json. 46 typed write handlers; reads and responses
// are not generated.
#![allow(dead_code, non_camel_case_types, non_snake_case)]
use serde::{Deserialize, Serialize};

use super::Optional;

// deserialize_with suppresses serde's implicit missing = None for required
// nullable fields, including nullable references hidden behind type aliases.
fn required<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    T::deserialize(deserializer)
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct ActionsReRunJobForWorkflowRunBodyObject46889909Fa {
    #[serde(
        rename = "enable_debug_logging",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_enable_debug_logging: Optional<bool>,
    #[serde(
        rename = "enable_debugger",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_enable_debugger: Optional<bool>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct ActionsReRunJobForWorkflowRunPathObjectC367F84033 {
    #[serde(rename = "job_id", deserialize_with = "required")]
    pub(super) field_job_id: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct ActionsReRunWorkflowBodyObject66C199Bd16 {
    #[serde(
        rename = "enable_debug_logging",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_enable_debug_logging: Optional<bool>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct ActionsReRunWorkflowPathObject9A7E0E9Ae2 {
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
    #[serde(rename = "run_id", deserialize_with = "required")]
    pub(super) field_run_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddAssigneesBodyObject8A57Ac64C2 {
    #[serde(
        rename = "assignees",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_assignees:
        Optional<Vec<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5A>>,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5A {
    V0(IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567),
    V1(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567 {
    #[serde(rename = "confidence", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_confidence: Optional<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678>,
    #[serde(rename = "login", deserialize_with = "required")]
    pub(super) field_login: String,
    #[serde(rename = "rationale", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_rationale: Optional<String>,
    #[serde(rename = "suggest", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_suggest: Optional<bool>,
}

#[derive(Deserialize, Serialize)]
pub(super) enum IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678
{
    #[serde(rename = "low")]
    V0,
    #[serde(rename = "medium")]
    V1,
    #[serde(rename = "high")]
    V2,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddAssigneesPathObject1339D510B7 {
    #[serde(rename = "issue_number", deserialize_with = "required")]
    pub(super) field_issue_number: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddBlockedByDependencyBodyObject18Fdf929B4 {
    #[serde(rename = "issue_id", deserialize_with = "required")]
    pub(super) field_issue_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4 {
    #[serde(
        rename = "issue_field_values",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_issue_field_values: Optional<
        Vec<IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4IssueFieldValuesItemObject4Dbd5F691B>,
    >,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4IssueFieldValuesItemObject4Dbd5F691B {
    #[serde(rename = "field_id", deserialize_with = "required")]
    pub(super) field_field_id: i64,
    #[serde(rename = "value", deserialize_with = "required")]
    pub(super) field_value: IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4IssueFieldValuesItemObject4Dbd5F691BValueUnio73621C37E5,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4IssueFieldValuesItemObject4Dbd5F691BValueUnio73621C37E5
{
    V0(String),
    V1(f64),
    V2(Vec<String>),
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesAddLabelsBodyUnion013Fcdb0Dc {
    V0(IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79),
    V1(Vec<String>),
    V2(Vec<IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79LabelsItemUnion93C34D5F4CVariantB7B9C815B6>),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79 {
    #[serde(
        rename = "labels",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_labels: Optional<
        Vec<IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79LabelsItemUnion93C34D5F4C>,
    >,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79LabelsItemUnion93C34D5F4C
{
    V0(IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79LabelsItemUnion93C34D5F4CVariantB7B9C815B6),
    V1(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddLabelsBodyUnion013Fcdb0DcVariant0ObjectF79A965E79LabelsItemUnion93C34D5F4CVariantB7B9C815B6 {
    #[serde(rename = "confidence", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_confidence: Optional<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678>,
    #[serde(rename = "name", deserialize_with = "required")]
    pub(super) field_name: String,
    #[serde(rename = "rationale", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_rationale: Optional<String>,
    #[serde(rename = "suggest", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_suggest: Optional<bool>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesAddSubIssueBodyObject6642381948 {
    #[serde(
        rename = "replace_parent",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_replace_parent: Optional<bool>,
    #[serde(rename = "sub_issue_id", deserialize_with = "required")]
    pub(super) field_sub_issue_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesApproveSuggestionPathObject56Ee57F6F0 {
    #[serde(rename = "issue_number", deserialize_with = "required")]
    pub(super) field_issue_number: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
    #[serde(rename = "suggestion_id", deserialize_with = "required")]
    pub(super) field_suggestion_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesCreateBodyObject09Ddfa994B {
    #[serde(
        rename = "assignee",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_assignee: Optional<Option<String>>,
    #[serde(
        rename = "assignees",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_assignees: Optional<Vec<String>>,
    #[serde(rename = "body", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_body: Optional<String>,
    #[serde(
        rename = "issue_field_values",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_issue_field_values: Optional<
        Vec<IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4IssueFieldValuesItemObject4Dbd5F691B>,
    >,
    #[serde(
        rename = "labels",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_labels:
        Optional<Vec<IssuesCreateBodyObject09Ddfa994BLabelsItemUnion3A54Fcbdb0>>,
    #[serde(
        rename = "milestone",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_milestone:
        Optional<Option<IssuesCreateBodyObject09Ddfa994BMilestoneUnionFbd93D8C28>>,
    #[serde(
        rename = "parent_issue_id",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_parent_issue_id: Optional<i64>,
    #[serde(rename = "title", deserialize_with = "required")]
    pub(super) field_title: IssuesCreateBodyObject09Ddfa994BMilestoneUnionFbd93D8C28,
    #[serde(rename = "type", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_type: Optional<Option<String>>,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesCreateBodyObject09Ddfa994BLabelsItemUnion3A54Fcbdb0 {
    V0(IssuesCreateBodyObject09Ddfa994BLabelsItemUnion3A54Fcbdb0Variant0Object1B188D3936),
    V1(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesCreateBodyObject09Ddfa994BLabelsItemUnion3A54Fcbdb0Variant0Object1B188D3936
{
    #[serde(
        rename = "color",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_color: Optional<Option<String>>,
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_description: Optional<Option<String>>,
    #[serde(rename = "id", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_id: Optional<i64>,
    #[serde(rename = "name", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_name: Optional<String>,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesCreateBodyObject09Ddfa994BMilestoneUnionFbd93D8C28 {
    V0(String),
    V1(i64),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesCreateCommentBodyObject8F436634D1 {
    #[serde(rename = "body", deserialize_with = "required")]
    pub(super) field_body: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesCreateLabelBodyObject5Cc29124C3 {
    #[serde(
        rename = "color",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_color: Optional<String>,
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_description: Optional<String>,
    #[serde(rename = "name", deserialize_with = "required")]
    pub(super) field_name: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesCreateMilestoneBodyObject78D8348334 {
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_description: Optional<String>,
    #[serde(
        rename = "due_on",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_due_on: Optional<String>,
    #[serde(
        rename = "state",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_state: Optional<IssuesCreateMilestoneBodyObject78D8348334StateEnumFb8626A13C>,
    #[serde(rename = "title", deserialize_with = "required")]
    pub(super) field_title: String,
}

#[derive(Deserialize, Serialize)]
pub(super) enum IssuesCreateMilestoneBodyObject78D8348334StateEnumFb8626A13C {
    #[serde(rename = "open")]
    V0,
    #[serde(rename = "closed")]
    V1,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesCreatePathObjectFd17340Fbd {
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesDeleteCommentPathObject7045Ca5141 {
    #[serde(rename = "comment_id", deserialize_with = "required")]
    pub(super) field_comment_id: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesDeleteIssueFieldValuePathObject8Df95649E0 {
    #[serde(rename = "issue_field_id", deserialize_with = "required")]
    pub(super) field_issue_field_id: i64,
    #[serde(rename = "issue_number", deserialize_with = "required")]
    pub(super) field_issue_number: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesDeleteLabelPathObjectA956022341 {
    #[serde(rename = "name", deserialize_with = "required")]
    pub(super) field_name: String,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesDeleteMilestonePathObjectF29B30935E {
    #[serde(rename = "milestone_number", deserialize_with = "required")]
    pub(super) field_milestone_number: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesLockBodyObject1Bcff982D2 {
    #[serde(
        rename = "lock_reason",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_lock_reason: Optional<IssuesLockBodyObject1Bcff982D2LockReasonEnum252Ea88Cc2>,
}

#[derive(Deserialize, Serialize)]
pub(super) enum IssuesLockBodyObject1Bcff982D2LockReasonEnum252Ea88Cc2 {
    #[serde(rename = "off-topic")]
    V0,
    #[serde(rename = "too heated")]
    V1,
    #[serde(rename = "resolved")]
    V2,
    #[serde(rename = "spam")]
    V3,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesRemoveAssigneesBodyObject0600286644 {
    #[serde(
        rename = "assignees",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_assignees: Optional<Vec<String>>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesRemoveDependencyBlockedByPathObject51365Ad951 {
    #[serde(rename = "issue_id", deserialize_with = "required")]
    pub(super) field_issue_id: i64,
    #[serde(rename = "issue_number", deserialize_with = "required")]
    pub(super) field_issue_number: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesRemoveLabelPathObject40F7C390Ef {
    #[serde(rename = "issue_number", deserialize_with = "required")]
    pub(super) field_issue_number: i64,
    #[serde(rename = "name", deserialize_with = "required")]
    pub(super) field_name: String,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesRemoveSubIssueBodyObject083D2E7Bec {
    #[serde(rename = "sub_issue_id", deserialize_with = "required")]
    pub(super) field_sub_issue_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesReprioritizeSubIssueBodyObject27479486Fc {
    #[serde(
        rename = "after_id",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_after_id: Optional<i64>,
    #[serde(
        rename = "before_id",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_before_id: Optional<i64>,
    #[serde(rename = "sub_issue_id", deserialize_with = "required")]
    pub(super) field_sub_issue_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesSetIssueFieldValuesBodyObject6744B6Aecb {
    #[serde(
        rename = "issue_field_values",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_issue_field_values: Optional<
        Vec<IssuesSetIssueFieldValuesBodyObject6744B6AecbIssueFieldValuesItemObject82Db9256Cb>,
    >,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesSetIssueFieldValuesBodyObject6744B6AecbIssueFieldValuesItemObject82Db9256Cb {
    #[serde(rename = "field_id", deserialize_with = "required")]
    pub(super) field_field_id: i64,
    #[serde(rename = "value", deserialize_with = "required")]
    pub(super) field_value: IssuesSetIssueFieldValuesBodyObject6744B6AecbIssueFieldValuesItemObject82Db9256CbValueUnioEb718355A1,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesSetIssueFieldValuesBodyObject6744B6AecbIssueFieldValuesItemObject82Db9256CbValueUnioEb718355A1
{
    V0(String),
    V1(f64),
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesSetLabelsBodyUnionD1C648Fc0A {
    V0(IssuesSetLabelsBodyUnionD1C648Fc0AVariant0Object0Dc6Df2Ff2),
    V1(IssuesSetLabelsBodyUnionD1C648Fc0AVariant1Object4A968B87Fa),
    V2(Vec<String>),
    V3(Vec<IssuesSetLabelsBodyUnionD1C648Fc0AVariant1Object4A968B87FaLabelsItemObjectCe2960Dd90>),
    V4(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesSetLabelsBodyUnionD1C648Fc0AVariant0Object0Dc6Df2Ff2 {
    #[serde(
        rename = "labels",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_labels: Optional<Vec<String>>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesSetLabelsBodyUnionD1C648Fc0AVariant1Object4A968B87Fa {
    #[serde(
        rename = "labels",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_labels: Optional<
        Vec<IssuesSetLabelsBodyUnionD1C648Fc0AVariant1Object4A968B87FaLabelsItemObjectCe2960Dd90>,
    >,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesSetLabelsBodyUnionD1C648Fc0AVariant1Object4A968B87FaLabelsItemObjectCe2960Dd90
{
    #[serde(rename = "name", deserialize_with = "required")]
    pub(super) field_name: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateBodyObjectCfa1B3Cce6 {
    #[serde(
        rename = "assignee",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_assignee: Optional<Option<String>>,
    #[serde(
        rename = "assignees",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_assignees:
        Optional<Vec<IssuesUpdateBodyObjectCfa1B3Cce6AssigneesItemUnion4955A0E76B>>,
    #[serde(rename = "body", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_body: Optional<Option<String>>,
    #[serde(
        rename = "duplicate_issue_id",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_duplicate_issue_id: Optional<i64>,
    #[serde(
        rename = "issue_field_values",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_issue_field_values:
        Optional<Vec<IssuesUpdateBodyObjectCfa1B3Cce6IssueFieldValuesItemObject3E16Aabbe0>>,
    #[serde(
        rename = "labels",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_labels:
        Optional<Vec<IssuesUpdateBodyObjectCfa1B3Cce6LabelsItemUnion0Cb516F037>>,
    #[serde(
        rename = "milestone",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_milestone:
        Optional<Option<IssuesCreateBodyObject09Ddfa994BMilestoneUnionFbd93D8C28>>,
    #[serde(
        rename = "state",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_state: Optional<IssuesCreateMilestoneBodyObject78D8348334StateEnumFb8626A13C>,
    #[serde(
        rename = "state_reason",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_state_reason:
        Optional<Option<IssuesUpdateBodyObjectCfa1B3Cce6StateReasonEnum2Ae43693Ac>>,
    #[serde(
        rename = "title",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_title:
        Optional<Option<IssuesCreateBodyObject09Ddfa994BMilestoneUnionFbd93D8C28>>,
    #[serde(rename = "type", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_type: Optional<Option<IssuesUpdateBodyObjectCfa1B3Cce6TypeUnion4A67884E57>>,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesUpdateBodyObjectCfa1B3Cce6AssigneesItemUnion4955A0E76B {
    V0(IssuesUpdateBodyObjectCfa1B3Cce6AssigneesItemUnion4955A0E76BVariant0ObjectB3E550429E),
    V1(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateBodyObjectCfa1B3Cce6AssigneesItemUnion4955A0E76BVariant0ObjectB3E550429E {
    #[serde(rename = "confidence", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_confidence: Optional<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678>,
    #[serde(rename = "login", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_login: Optional<String>,
    #[serde(rename = "rationale", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_rationale: Optional<String>,
    #[serde(rename = "suggest", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_suggest: Optional<bool>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateBodyObjectCfa1B3Cce6IssueFieldValuesItemObject3E16Aabbe0 {
    #[serde(rename = "confidence", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_confidence: Optional<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678>,
    #[serde(rename = "field_id", deserialize_with = "required")]
    pub(super) field_field_id: i64,
    #[serde(rename = "rationale", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_rationale: Optional<String>,
    #[serde(rename = "suggest", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_suggest: Optional<bool>,
    #[serde(rename = "value", deserialize_with = "required")]
    pub(super) field_value: IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4IssueFieldValuesItemObject4Dbd5F691BValueUnio73621C37E5,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesUpdateBodyObjectCfa1B3Cce6LabelsItemUnion0Cb516F037 {
    V0(IssuesUpdateBodyObjectCfa1B3Cce6LabelsItemUnion0Cb516F037Variant0Object4Df2F7F7Df),
    V1(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateBodyObjectCfa1B3Cce6LabelsItemUnion0Cb516F037Variant0Object4Df2F7F7Df {
    #[serde(rename = "color", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_color: Optional<Option<String>>,
    #[serde(rename = "confidence", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_confidence: Optional<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678>,
    #[serde(rename = "description", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_description: Optional<Option<String>>,
    #[serde(rename = "id", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_id: Optional<i64>,
    #[serde(rename = "name", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_name: Optional<String>,
    #[serde(rename = "rationale", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_rationale: Optional<String>,
    #[serde(rename = "suggest", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_suggest: Optional<bool>,
}

#[derive(Deserialize, Serialize)]
pub(super) enum IssuesUpdateBodyObjectCfa1B3Cce6StateReasonEnum2Ae43693Ac {
    #[serde(rename = "completed")]
    V0,
    #[serde(rename = "not_planned")]
    V1,
    #[serde(rename = "duplicate")]
    V2,
    #[serde(rename = "reopened")]
    V3,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum IssuesUpdateBodyObjectCfa1B3Cce6TypeUnion4A67884E57 {
    V0(IssuesUpdateBodyObjectCfa1B3Cce6TypeUnion4A67884E57Variant0Object77B4Fce2F2),
    V1(String),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateBodyObjectCfa1B3Cce6TypeUnion4A67884E57Variant0Object77B4Fce2F2 {
    #[serde(rename = "confidence", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_confidence: Optional<IssuesAddAssigneesBodyObject8A57Ac64C2AssigneesItemUnion7C47C0Bd5AVariant0Object4608Ab2567Da7D33F678>,
    #[serde(rename = "rationale", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_rationale: Optional<String>,
    #[serde(rename = "suggest", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_suggest: Optional<bool>,
    #[serde(rename = "value", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_value: Optional<Option<String>>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateLabelBodyObject4A2C599816 {
    #[serde(
        rename = "archived",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_archived: Optional<bool>,
    #[serde(
        rename = "color",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_color: Optional<String>,
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_description: Optional<String>,
    #[serde(
        rename = "new_name",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_new_name: Optional<String>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct IssuesUpdateMilestoneBodyObject9B8Ad66395 {
    #[serde(
        rename = "description",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_description: Optional<String>,
    #[serde(
        rename = "due_on",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_due_on: Optional<String>,
    #[serde(
        rename = "state",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_state: Optional<IssuesCreateMilestoneBodyObject78D8348334StateEnumFb8626A13C>,
    #[serde(
        rename = "title",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_title: Optional<String>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsCreateBodyObject1Fc3Cab02C {
    #[serde(rename = "base", deserialize_with = "required")]
    pub(super) field_base: String,
    #[serde(rename = "body", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_body: Optional<String>,
    #[serde(
        rename = "draft",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_draft: Optional<bool>,
    #[serde(rename = "head", deserialize_with = "required")]
    pub(super) field_head: String,
    #[serde(
        rename = "head_repo",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_head_repo: Optional<String>,
    #[serde(
        rename = "issue",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_issue: Optional<i64>,
    #[serde(
        rename = "maintainer_can_modify",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_maintainer_can_modify: Optional<bool>,
    #[serde(
        rename = "title",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_title: Optional<String>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsCreateReplyForReviewCommentPathObjectD4E6C116C1 {
    #[serde(rename = "comment_id", deserialize_with = "required")]
    pub(super) field_comment_id: i64,
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "pull_number", deserialize_with = "required")]
    pub(super) field_pull_number: i64,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsCreateReviewBodyObject6Ce948218F {
    #[serde(rename = "body", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_body: Optional<String>,
    #[serde(
        rename = "comments",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_comments:
        Optional<Vec<PullsCreateReviewBodyObject6Ce948218FCommentsItemObject5B36E38Cbb>>,
    #[serde(
        rename = "commit_id",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_commit_id: Optional<String>,
    #[serde(
        rename = "event",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_event: Optional<PullsCreateReviewBodyObject6Ce948218FEventEnum91E02Fb3B8>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsCreateReviewBodyObject6Ce948218FCommentsItemObject5B36E38Cbb {
    #[serde(rename = "body", deserialize_with = "required")]
    pub(super) field_body: String,
    #[serde(rename = "line", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_line: Optional<i64>,
    #[serde(rename = "path", deserialize_with = "required")]
    pub(super) field_path: String,
    #[serde(
        rename = "position",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_position: Optional<i64>,
    #[serde(rename = "side", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_side: Optional<String>,
    #[serde(
        rename = "start_line",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_start_line: Optional<i64>,
    #[serde(
        rename = "start_side",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_start_side: Optional<String>,
}

#[derive(Deserialize, Serialize)]
pub(super) enum PullsCreateReviewBodyObject6Ce948218FEventEnum91E02Fb3B8 {
    #[serde(rename = "APPROVE")]
    V0,
    #[serde(rename = "REQUEST_CHANGES")]
    V1,
    #[serde(rename = "COMMENT")]
    V2,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsCreateReviewCommentBodyObject8Ca2F6D53F {
    #[serde(rename = "body", deserialize_with = "required")]
    pub(super) field_body: String,
    #[serde(rename = "commit_id", deserialize_with = "required")]
    pub(super) field_commit_id: String,
    #[serde(
        rename = "in_reply_to",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_in_reply_to: Optional<i64>,
    #[serde(rename = "line", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_line: Optional<i64>,
    #[serde(rename = "path", deserialize_with = "required")]
    pub(super) field_path: String,
    #[serde(
        rename = "position",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_position: Optional<i64>,
    #[serde(rename = "side", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_side: Optional<PullsCreateReviewCommentBodyObject8Ca2F6D53FSideEnum55D8467Edc>,
    #[serde(
        rename = "start_line",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_start_line: Optional<i64>,
    #[serde(
        rename = "start_side",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_start_side:
        Optional<PullsCreateReviewCommentBodyObject8Ca2F6D53FStartSideEnumBb7B40Eb1E>,
    #[serde(
        rename = "subject_type",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_subject_type:
        Optional<PullsCreateReviewCommentBodyObject8Ca2F6D53FSubjectTypeEnumAd53Af9Fb2>,
}

#[derive(Deserialize, Serialize)]
pub(super) enum PullsCreateReviewCommentBodyObject8Ca2F6D53FSideEnum55D8467Edc {
    #[serde(rename = "LEFT")]
    V0,
    #[serde(rename = "RIGHT")]
    V1,
}

#[derive(Deserialize, Serialize)]
pub(super) enum PullsCreateReviewCommentBodyObject8Ca2F6D53FStartSideEnumBb7B40Eb1E {
    #[serde(rename = "LEFT")]
    V0,
    #[serde(rename = "RIGHT")]
    V1,
    #[serde(rename = "side")]
    V2,
}

#[derive(Deserialize, Serialize)]
pub(super) enum PullsCreateReviewCommentBodyObject8Ca2F6D53FSubjectTypeEnumAd53Af9Fb2 {
    #[serde(rename = "line")]
    V0,
    #[serde(rename = "file")]
    V1,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsCreateReviewPathObject7013Db9B8A {
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "pull_number", deserialize_with = "required")]
    pub(super) field_pull_number: i64,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsDeletePendingReviewPathObjectEb6C790D16 {
    #[serde(rename = "owner", deserialize_with = "required")]
    pub(super) field_owner: String,
    #[serde(rename = "pull_number", deserialize_with = "required")]
    pub(super) field_pull_number: i64,
    #[serde(rename = "repo", deserialize_with = "required")]
    pub(super) field_repo: String,
    #[serde(rename = "review_id", deserialize_with = "required")]
    pub(super) field_review_id: i64,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsRemoveRequestedReviewersBodyObjectF0E3Ebf4E6 {
    #[serde(rename = "reviewers", deserialize_with = "required")]
    pub(super) field_reviewers: Vec<String>,
    #[serde(
        rename = "team_reviewers",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_team_reviewers: Optional<Vec<String>>,
}

#[derive(Deserialize, Serialize)]
#[serde(untagged)]
pub(super) enum PullsRequestReviewersBodyUnion7F4Ff9E9F4 {
    V0(PullsRemoveRequestedReviewersBodyObjectF0E3Ebf4E6),
    V1(PullsRequestReviewersBodyUnion7F4Ff9E9F4Variant1ObjectD83722Bdbb),
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsRequestReviewersBodyUnion7F4Ff9E9F4Variant1ObjectD83722Bdbb {
    #[serde(
        rename = "reviewers",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_reviewers: Optional<Vec<String>>,
    #[serde(rename = "team_reviewers", deserialize_with = "required")]
    pub(super) field_team_reviewers: Vec<String>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsSubmitReviewBodyObjectDd2C0608Fd {
    #[serde(rename = "body", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_body: Optional<String>,
    #[serde(rename = "event", deserialize_with = "required")]
    pub(super) field_event: PullsCreateReviewBodyObject6Ce948218FEventEnum91E02Fb3B8,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct PullsUpdateBodyObject695Ea676B8 {
    #[serde(rename = "base", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_base: Optional<String>,
    #[serde(rename = "body", default, skip_serializing_if = "Optional::is_missing")]
    pub(super) field_body: Optional<String>,
    #[serde(
        rename = "maintainer_can_modify",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_maintainer_can_modify: Optional<bool>,
    #[serde(
        rename = "state",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_state: Optional<IssuesCreateMilestoneBodyObject78D8348334StateEnumFb8626A13C>,
    #[serde(
        rename = "title",
        default,
        skip_serializing_if = "Optional::is_missing"
    )]
    pub(super) field_title: Optional<String>,
}

pub(super) type ActionsReRunJobForWorkflowRunPath =
    ActionsReRunJobForWorkflowRunPathObjectC367F84033;

pub(super) type ActionsReRunJobForWorkflowRunBody =
    Option<ActionsReRunJobForWorkflowRunBodyObject46889909Fa>;

pub(super) type ActionsReRunWorkflowPath = ActionsReRunWorkflowPathObject9A7E0E9Ae2;

pub(super) type ActionsReRunWorkflowBody = Option<ActionsReRunWorkflowBodyObject66C199Bd16>;

pub(super) type ActionsReRunWorkflowFailedJobsPath = ActionsReRunWorkflowPathObject9A7E0E9Ae2;

pub(super) type ActionsReRunWorkflowFailedJobsBody =
    Option<ActionsReRunWorkflowBodyObject66C199Bd16>;

pub(super) type IssuesAddAssigneesPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesAddAssigneesBody = IssuesAddAssigneesBodyObject8A57Ac64C2;

pub(super) type IssuesAddBlockedByDependencyPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesAddBlockedByDependencyBody = IssuesAddBlockedByDependencyBodyObject18Fdf929B4;

pub(super) type IssuesAddIssueFieldValuesPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesAddIssueFieldValuesBody = IssuesAddIssueFieldValuesBodyObjectE8D64Ddab4;

pub(super) type IssuesAddLabelsPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesAddLabelsBody = IssuesAddLabelsBodyUnion013Fcdb0Dc;

pub(super) type IssuesAddSubIssuePath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesAddSubIssueBody = IssuesAddSubIssueBodyObject6642381948;

pub(super) type IssuesApproveSuggestionPath = IssuesApproveSuggestionPathObject56Ee57F6F0;

pub(super) type IssuesCreatePath = IssuesCreatePathObjectFd17340Fbd;

pub(super) type IssuesCreateBody = IssuesCreateBodyObject09Ddfa994B;

pub(super) type IssuesCreateCommentPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesCreateCommentBody = IssuesCreateCommentBodyObject8F436634D1;

pub(super) type IssuesCreateLabelPath = IssuesCreatePathObjectFd17340Fbd;

pub(super) type IssuesCreateLabelBody = IssuesCreateLabelBodyObject5Cc29124C3;

pub(super) type IssuesCreateMilestonePath = IssuesCreatePathObjectFd17340Fbd;

pub(super) type IssuesCreateMilestoneBody = IssuesCreateMilestoneBodyObject78D8348334;

pub(super) type IssuesDeleteCommentPath = IssuesDeleteCommentPathObject7045Ca5141;

pub(super) type IssuesDeleteIssueFieldValuePath = IssuesDeleteIssueFieldValuePathObject8Df95649E0;

pub(super) type IssuesDeleteLabelPath = IssuesDeleteLabelPathObjectA956022341;

pub(super) type IssuesDeleteMilestonePath = IssuesDeleteMilestonePathObjectF29B30935E;

pub(super) type IssuesDismissSuggestionPath = IssuesApproveSuggestionPathObject56Ee57F6F0;

pub(super) type IssuesLockPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesLockBody = Option<IssuesLockBodyObject1Bcff982D2>;

pub(super) type IssuesPinCommentPath = IssuesDeleteCommentPathObject7045Ca5141;

pub(super) type IssuesRemoveAllLabelsPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesRemoveAssigneesPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesRemoveAssigneesBody = IssuesRemoveAssigneesBodyObject0600286644;

pub(super) type IssuesRemoveDependencyBlockedByPath =
    IssuesRemoveDependencyBlockedByPathObject51365Ad951;

pub(super) type IssuesRemoveLabelPath = IssuesRemoveLabelPathObject40F7C390Ef;

pub(super) type IssuesRemoveSubIssuePath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesRemoveSubIssueBody = IssuesRemoveSubIssueBodyObject083D2E7Bec;

pub(super) type IssuesReprioritizeSubIssuePath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesReprioritizeSubIssueBody = IssuesReprioritizeSubIssueBodyObject27479486Fc;

pub(super) type IssuesSetIssueFieldValuesPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesSetIssueFieldValuesBody = IssuesSetIssueFieldValuesBodyObject6744B6Aecb;

pub(super) type IssuesSetLabelsPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesSetLabelsBody = IssuesSetLabelsBodyUnionD1C648Fc0A;

pub(super) type IssuesUnlockPath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesUnpinCommentPath = IssuesDeleteCommentPathObject7045Ca5141;

pub(super) type IssuesUpdatePath = IssuesAddAssigneesPathObject1339D510B7;

pub(super) type IssuesUpdateBody = IssuesUpdateBodyObjectCfa1B3Cce6;

pub(super) type IssuesUpdateCommentPath = IssuesDeleteCommentPathObject7045Ca5141;

pub(super) type IssuesUpdateCommentBody = IssuesCreateCommentBodyObject8F436634D1;

pub(super) type IssuesUpdateLabelPath = IssuesDeleteLabelPathObjectA956022341;

pub(super) type IssuesUpdateLabelBody = IssuesUpdateLabelBodyObject4A2C599816;

pub(super) type IssuesUpdateMilestonePath = IssuesDeleteMilestonePathObjectF29B30935E;

pub(super) type IssuesUpdateMilestoneBody = IssuesUpdateMilestoneBodyObject9B8Ad66395;

pub(super) type PullsCreatePath = IssuesCreatePathObjectFd17340Fbd;

pub(super) type PullsCreateBody = PullsCreateBodyObject1Fc3Cab02C;

pub(super) type PullsCreateReplyForReviewCommentPath =
    PullsCreateReplyForReviewCommentPathObjectD4E6C116C1;

pub(super) type PullsCreateReplyForReviewCommentBody = IssuesCreateCommentBodyObject8F436634D1;

pub(super) type PullsCreateReviewPath = PullsCreateReviewPathObject7013Db9B8A;

pub(super) type PullsCreateReviewBody = PullsCreateReviewBodyObject6Ce948218F;

pub(super) type PullsCreateReviewCommentPath = PullsCreateReviewPathObject7013Db9B8A;

pub(super) type PullsCreateReviewCommentBody = PullsCreateReviewCommentBodyObject8Ca2F6D53F;

pub(super) type PullsDeletePendingReviewPath = PullsDeletePendingReviewPathObjectEb6C790D16;

pub(super) type PullsDeleteReviewCommentPath = IssuesDeleteCommentPathObject7045Ca5141;

pub(super) type PullsRemoveRequestedReviewersPath = PullsCreateReviewPathObject7013Db9B8A;

pub(super) type PullsRemoveRequestedReviewersBody =
    PullsRemoveRequestedReviewersBodyObjectF0E3Ebf4E6;

pub(super) type PullsRequestReviewersPath = PullsCreateReviewPathObject7013Db9B8A;

pub(super) type PullsRequestReviewersBody = PullsRequestReviewersBodyUnion7F4Ff9E9F4;

pub(super) type PullsSubmitReviewPath = PullsDeletePendingReviewPathObjectEb6C790D16;

pub(super) type PullsSubmitReviewBody = PullsSubmitReviewBodyObjectDd2C0608Fd;

pub(super) type PullsUpdatePath = PullsCreateReviewPathObject7013Db9B8A;

pub(super) type PullsUpdateBody = PullsUpdateBodyObject695Ea676B8;

pub(super) type PullsUpdateReviewPath = PullsDeletePendingReviewPathObjectEb6C790D16;

pub(super) type PullsUpdateReviewBody = IssuesCreateCommentBodyObject8F436634D1;

pub(super) type PullsUpdateReviewCommentPath = IssuesDeleteCommentPathObject7045Ca5141;

pub(super) type PullsUpdateReviewCommentBody = IssuesCreateCommentBodyObject8F436634D1;

pub(super) fn actions_re_run_job_for_workflow_run(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<ActionsReRunJobForWorkflowRunPath, ActionsReRunJobForWorkflowRunBody>(
            request, false, true,
        )
        .await
    })
}

pub(super) fn actions_re_run_workflow(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<ActionsReRunWorkflowPath, ActionsReRunWorkflowBody>(request, false, true)
            .await
    })
}

pub(super) fn actions_re_run_workflow_failed_jobs(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<ActionsReRunWorkflowFailedJobsPath, ActionsReRunWorkflowFailedJobsBody>(
            request, false, true,
        )
        .await
    })
}

pub(super) fn issues_add_assignees(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesAddAssigneesPath, IssuesAddAssigneesBody>(request, false, true).await
    })
}

pub(super) fn issues_add_blocked_by_dependency(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesAddBlockedByDependencyPath, IssuesAddBlockedByDependencyBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn issues_add_issue_field_values(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesAddIssueFieldValuesPath, IssuesAddIssueFieldValuesBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn issues_add_labels(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesAddLabelsPath, IssuesAddLabelsBody>(request, false, true).await
    })
}

pub(super) fn issues_add_sub_issue(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesAddSubIssuePath, IssuesAddSubIssueBody>(request, true, true).await
    })
}

pub(super) fn issues_approve_suggestion(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<IssuesApproveSuggestionPath, ()>(request, false, false).await },
    )
}

pub(super) fn issues_create(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesCreatePath, IssuesCreateBody>(request, true, true).await
    })
}

pub(super) fn issues_create_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesCreateCommentPath, IssuesCreateCommentBody>(request, true, true).await
    })
}

pub(super) fn issues_create_label(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesCreateLabelPath, IssuesCreateLabelBody>(request, true, true).await
    })
}

pub(super) fn issues_create_milestone(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesCreateMilestonePath, IssuesCreateMilestoneBody>(request, true, true)
            .await
    })
}

pub(super) fn issues_delete_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<IssuesDeleteCommentPath, ()>(request, false, false).await },
    )
}

pub(super) fn issues_delete_issue_field_value(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesDeleteIssueFieldValuePath, ()>(request, false, false).await
    })
}

pub(super) fn issues_delete_label(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move { super::typed::<IssuesDeleteLabelPath, ()>(request, false, false).await })
}

pub(super) fn issues_delete_milestone(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<IssuesDeleteMilestonePath, ()>(request, false, false).await },
    )
}

pub(super) fn issues_dismiss_suggestion(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<IssuesDismissSuggestionPath, ()>(request, false, false).await },
    )
}

pub(super) fn issues_lock(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<IssuesLockPath, IssuesLockBody>(request, false, true).await },
    )
}

pub(super) fn issues_pin_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move { super::typed::<IssuesPinCommentPath, ()>(request, false, false).await })
}

pub(super) fn issues_remove_all_labels(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<IssuesRemoveAllLabelsPath, ()>(request, false, false).await },
    )
}

pub(super) fn issues_remove_assignees(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesRemoveAssigneesPath, IssuesRemoveAssigneesBody>(request, false, true)
            .await
    })
}

pub(super) fn issues_remove_dependency_blocked_by(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesRemoveDependencyBlockedByPath, ()>(request, false, false).await
    })
}

pub(super) fn issues_remove_label(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move { super::typed::<IssuesRemoveLabelPath, ()>(request, false, false).await })
}

pub(super) fn issues_remove_sub_issue(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesRemoveSubIssuePath, IssuesRemoveSubIssueBody>(request, true, true)
            .await
    })
}

pub(super) fn issues_reprioritize_sub_issue(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesReprioritizeSubIssuePath, IssuesReprioritizeSubIssueBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn issues_set_issue_field_values(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesSetIssueFieldValuesPath, IssuesSetIssueFieldValuesBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn issues_set_labels(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesSetLabelsPath, IssuesSetLabelsBody>(request, false, true).await
    })
}

pub(super) fn issues_unlock(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move { super::typed::<IssuesUnlockPath, ()>(request, false, false).await })
}

pub(super) fn issues_unpin_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move { super::typed::<IssuesUnpinCommentPath, ()>(request, false, false).await })
}

pub(super) fn issues_update(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesUpdatePath, IssuesUpdateBody>(request, false, true).await
    })
}

pub(super) fn issues_update_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesUpdateCommentPath, IssuesUpdateCommentBody>(request, true, true).await
    })
}

pub(super) fn issues_update_label(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesUpdateLabelPath, IssuesUpdateLabelBody>(request, false, true).await
    })
}

pub(super) fn issues_update_milestone(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<IssuesUpdateMilestonePath, IssuesUpdateMilestoneBody>(request, false, true)
            .await
    })
}

pub(super) fn pulls_create(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<PullsCreatePath, PullsCreateBody>(request, true, true).await },
    )
}

pub(super) fn pulls_create_reply_for_review_comment(
    request: super::Request,
) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsCreateReplyForReviewCommentPath, PullsCreateReplyForReviewCommentBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn pulls_create_review(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsCreateReviewPath, PullsCreateReviewBody>(request, false, true).await
    })
}

pub(super) fn pulls_create_review_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsCreateReviewCommentPath, PullsCreateReviewCommentBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn pulls_delete_pending_review(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsDeletePendingReviewPath, ()>(request, false, false).await
    })
}

pub(super) fn pulls_delete_review_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsDeleteReviewCommentPath, ()>(request, false, false).await
    })
}

pub(super) fn pulls_remove_requested_reviewers(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsRemoveRequestedReviewersPath, PullsRemoveRequestedReviewersBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn pulls_request_reviewers(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsRequestReviewersPath, PullsRequestReviewersBody>(request, false, true)
            .await
    })
}

pub(super) fn pulls_submit_review(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsSubmitReviewPath, PullsSubmitReviewBody>(request, true, true).await
    })
}

pub(super) fn pulls_update(request: super::Request) -> super::HandlerFuture {
    Box::pin(
        async move { super::typed::<PullsUpdatePath, PullsUpdateBody>(request, false, true).await },
    )
}

pub(super) fn pulls_update_review(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsUpdateReviewPath, PullsUpdateReviewBody>(request, true, true).await
    })
}

pub(super) fn pulls_update_review_comment(request: super::Request) -> super::HandlerFuture {
    Box::pin(async move {
        super::typed::<PullsUpdateReviewCommentPath, PullsUpdateReviewCommentBody>(
            request, true, true,
        )
        .await
    })
}

pub(super) fn handler(group: &str, name: &str) -> Option<super::Handler> {
    match (group, name) {
        ("actions", "re_run_job_for_workflow_run") => Some(actions_re_run_job_for_workflow_run),
        ("actions", "re_run_workflow") => Some(actions_re_run_workflow),
        ("actions", "re_run_workflow_failed_jobs") => Some(actions_re_run_workflow_failed_jobs),
        ("issues", "add_assignees") => Some(issues_add_assignees),
        ("issues", "add_blocked_by_dependency") => Some(issues_add_blocked_by_dependency),
        ("issues", "add_issue_field_values") => Some(issues_add_issue_field_values),
        ("issues", "add_labels") => Some(issues_add_labels),
        ("issues", "add_sub_issue") => Some(issues_add_sub_issue),
        ("issues", "approve_suggestion") => Some(issues_approve_suggestion),
        ("issues", "create") => Some(issues_create),
        ("issues", "create_comment") => Some(issues_create_comment),
        ("issues", "create_label") => Some(issues_create_label),
        ("issues", "create_milestone") => Some(issues_create_milestone),
        ("issues", "delete_comment") => Some(issues_delete_comment),
        ("issues", "delete_issue_field_value") => Some(issues_delete_issue_field_value),
        ("issues", "delete_label") => Some(issues_delete_label),
        ("issues", "delete_milestone") => Some(issues_delete_milestone),
        ("issues", "dismiss_suggestion") => Some(issues_dismiss_suggestion),
        ("issues", "lock") => Some(issues_lock),
        ("issues", "pin_comment") => Some(issues_pin_comment),
        ("issues", "remove_all_labels") => Some(issues_remove_all_labels),
        ("issues", "remove_assignees") => Some(issues_remove_assignees),
        ("issues", "remove_dependency_blocked_by") => Some(issues_remove_dependency_blocked_by),
        ("issues", "remove_label") => Some(issues_remove_label),
        ("issues", "remove_sub_issue") => Some(issues_remove_sub_issue),
        ("issues", "reprioritize_sub_issue") => Some(issues_reprioritize_sub_issue),
        ("issues", "set_issue_field_values") => Some(issues_set_issue_field_values),
        ("issues", "set_labels") => Some(issues_set_labels),
        ("issues", "unlock") => Some(issues_unlock),
        ("issues", "unpin_comment") => Some(issues_unpin_comment),
        ("issues", "update") => Some(issues_update),
        ("issues", "update_comment") => Some(issues_update_comment),
        ("issues", "update_label") => Some(issues_update_label),
        ("issues", "update_milestone") => Some(issues_update_milestone),
        ("pulls", "create") => Some(pulls_create),
        ("pulls", "create_reply_for_review_comment") => Some(pulls_create_reply_for_review_comment),
        ("pulls", "create_review") => Some(pulls_create_review),
        ("pulls", "create_review_comment") => Some(pulls_create_review_comment),
        ("pulls", "delete_pending_review") => Some(pulls_delete_pending_review),
        ("pulls", "delete_review_comment") => Some(pulls_delete_review_comment),
        ("pulls", "remove_requested_reviewers") => Some(pulls_remove_requested_reviewers),
        ("pulls", "request_reviewers") => Some(pulls_request_reviewers),
        ("pulls", "submit_review") => Some(pulls_submit_review),
        ("pulls", "update") => Some(pulls_update),
        ("pulls", "update_review") => Some(pulls_update_review),
        ("pulls", "update_review_comment") => Some(pulls_update_review_comment),
        _ => None,
    }
}
