[package]
name = "rho-image"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rho-inference.workspace = true
anyhow.workspace = true
image = { version = "0.25", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
tokio.workspace = true

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
