"""Selected entries from ghapi 2.1.5 GitHub OpenAPI metadata (Apache-2.0)."""
spec = {'base_url': 'https://api.github.com',
 'ops': [{'group': 'checks',
          'name': 'list_for_ref',
          'path': '/repos/{owner}/{repo}/commits/{ref}/check-runs',
          'verb': 'GET',
          'summary': 'List check runs for a Git reference',
          'route_params': ['owner', 'repo', 'ref'],
          'query_params': ['per_page', 'page'],
          'required_params': ['owner', 'ref', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'ref': 'str', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'ref': 'Octo accepts a 40-character commit SHA.',
                         'per_page': 'The number of results per page (max 100). For more information, '
                                     'see "[Using pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see '
                                 '"[Using pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/checks/runs#list-check-runs-for-a-git-reference'},
         {'group': 'repos',
          'name': 'get_combined_status_for_ref',
          'path': '/repos/{owner}/{repo}/commits/{ref}/status',
          'verb': 'GET',
          'summary': 'Get the combined status for a specific reference',
          'route_params': ['owner', 'repo', 'ref'],
          'query_params': [],
          'required_params': ['owner', 'ref', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'ref': 'str'},
          'param_defaults': {},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'ref': 'Octo accepts a 40-character commit SHA.'},
          'docs_url': 'https://docs.github.com/rest/commits/statuses#get-the-combined-status-for-a-specific-reference'},
         {'group': 'issues',
          'name': 'list_for_repo',
          'path': '/repos/{owner}/{repo}/issues',
          'verb': 'GET',
          'summary': 'List repository issues',
          'route_params': ['owner', 'repo'],
          'query_params': ['state', 'per_page', 'page'],
          'required_params': ['owner', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'state': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'state': 'open', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'state': 'Indicates the state of the issues to return.',
                         'per_page': 'The number of results per page (max 100). For more information, '
                                     'see "[Using pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see '
                                 '"[Using pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/issues/issues#list-repository-issues'},
         {'group': 'issues',
          'name': 'get',
          'path': '/repos/{owner}/{repo}/issues/{issue_number}',
          'verb': 'GET',
          'summary': 'Get an issue',
          'route_params': ['owner', 'repo', 'issue_number'],
          'required_params': ['issue_number', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'issue_number': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'issue_number': 'The number that identifies the issue.'},
          'docs_url': 'https://docs.github.com/rest/issues/issues#get-an-issue'},
         {'group': 'pulls',
          'name': 'list',
          'path': '/repos/{owner}/{repo}/pulls',
          'verb': 'GET',
          'summary': 'List pull requests',
          'route_params': ['owner', 'repo'],
          'query_params': ['state', 'per_page', 'page'],
          'required_params': ['owner', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'state': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'state': 'open', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'state': 'Either `open`, `closed`, or `all` to filter by state.',
                         'per_page': 'The number of results per page (max 100). For more information, '
                                     'see "[Using pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see '
                                 '"[Using pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#list-pull-requests'},
         {'group': 'pulls',
          'name': 'create',
          'path': '/repos/{owner}/{repo}/pulls',
          'verb': 'POST',
          'summary': 'Create a pull request',
          'route_params': ['owner', 'repo'],
          'body_params': ['title', 'head', 'base', 'body', 'maintainer_can_modify', 'draft'],
          'request_content_type': 'application/json',
          'required_params': ['base', 'head', 'owner', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'title': 'str',
                          'head': 'str',
                          'base': 'str',
                          'body': 'str',
                          'maintainer_can_modify': 'bool',
                          'draft': 'bool'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'title': 'The title of the new pull request. Required unless `issue` is '
                                  'specified.',
                         'head': 'The name of the branch where your changes are implemented. For '
                                 'cross-repository pull requests in the same network, namespace `head` '
                                 'with a user like this: `username:branch`.',
                         'base': 'The name of the branch you want the changes pulled into. This should '
                                 'be an existing branch on the current repository. You cannot submit a '
                                 'pull request to one repository that requests a merge to a base of '
                                 'another repository.',
                         'body': 'The contents of the pull request.',
                         'maintainer_can_modify': 'Indicates whether [maintainers can '
                                                  'modify](https://docs.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) '
                                                  'the pull request.',
                         'draft': 'Indicates whether the pull request is a draft. See "[Draft Pull '
                                  'Requests](https://docs.github.com/articles/about-pull-requests#draft-pull-requests)" '
                                  'in the GitHub Help documentation to learn more.'},
          'body_examples': {'default': {'summary': '',
                                        'value': {'title': 'Amazing new feature',
                                                  'body': 'Please pull these awesome changes in!',
                                                  'head': 'octocat:new-feature',
                                                  'base': 'master'}}},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#create-a-pull-request'},
         {'group': 'pulls',
          'name': 'get',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}',
          'verb': 'GET',
          'summary': 'Get a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'pull_number': 'The number that identifies the pull request.'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#get-a-pull-request'},
         {'group': 'pulls',
          'name': 'update',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}',
          'verb': 'PATCH',
          'summary': 'Update a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'body_params': ['base', 'title', 'body'],
          'request_content_type': 'application/json',
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'base': 'str', 'title': 'str', 'body': 'str'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'base': 'The name of the branch you want the changes pulled into.',
                         'title': 'The title of the pull request.',
                         'body': 'The contents of the pull request.'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#update-a-pull-request'},
         {'group': 'issues',
          'name': 'list_comments',
          'path': '/repos/{owner}/{repo}/issues/{issue_number}/comments',
          'verb': 'GET',
          'summary': 'List issue comments',
          'route_params': ['owner', 'repo', 'issue_number'],
          'query_params': ['since', 'per_page', 'page'],
          'required_params': ['issue_number', 'owner', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'issue_number': 'int',
                          'since': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'issue_number': 'The number that identifies the issue.',
                         'since': 'Only show results that were last updated after the given time. This is a timestamp '
                                  'in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: '
                                  '`YYYY-MM-DDTHH:MM:SSZ`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/issues/comments#list-issue-comments'},
         {'group': 'issues',
          'name': 'create_comment',
          'path': '/repos/{owner}/{repo}/issues/{issue_number}/comments',
          'verb': 'POST',
          'summary': 'Create an issue comment',
          'route_params': ['owner', 'repo', 'issue_number'],
          'body_params': ['body'],
          'request_content_type': 'application/json',
          'required_params': ['body', 'issue_number', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'issue_number': 'int', 'body': 'str'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'issue_number': 'The number that identifies the issue.',
                         'body': 'The contents of the comment.'},
          'body_examples': {'default': {'summary': '', 'value': {'body': 'Me too'}}},
          'docs_url': 'https://docs.github.com/rest/issues/comments#create-an-issue-comment'},
         {'group': 'pulls',
          'name': 'list_reviews',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/reviews',
          'verb': 'GET',
          'summary': 'List reviews for a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'query_params': ['per_page', 'page'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/reviews#list-reviews-for-a-pull-request'},
         {'group': 'pulls',
          'name': 'list_review_comments',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/comments',
          'verb': 'GET',
          'summary': 'List review comments on a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'query_params': ['sort', 'direction', 'since', 'per_page', 'page'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'pull_number': 'int',
                          'sort': 'str',
                          'direction': 'str',
                          'since': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'sort': 'created', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'sort': 'The property to sort the results by.',
                         'direction': 'The direction to sort results. Ignored without `sort` parameter.',
                         'since': 'Only show results that were last updated after the given time. This is a timestamp '
                                  'in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: '
                                  '`YYYY-MM-DDTHH:MM:SSZ`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/comments#list-review-comments-on-a-pull-request'},
         {'group': 'pulls',
          'name': 'create_reply_for_review_comment',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies',
          'verb': 'POST',
          'summary': 'Create a reply for a review comment',
          'route_params': ['owner', 'repo', 'pull_number', 'comment_id'],
          'body_params': ['body'],
          'request_content_type': 'application/json',
          'required_params': ['body', 'comment_id', 'owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'comment_id': 'int', 'body': 'str'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'comment_id': 'The unique identifier of the comment.',
                         'body': 'The text of the review comment.'},
          'body_examples': {'default': {'summary': '', 'value': {'body': 'Great stuff!'}}},
          'docs_url': 'https://docs.github.com/rest/pulls/comments#create-a-reply-for-a-review-comment'},
         {'group': 'actions',
          'name': 'get_job_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/jobs/{job_id}',
          'verb': 'GET',
          'summary': 'Get a job for a workflow run',
          'route_params': ['owner', 'repo', 'job_id'],
          'required_params': ['job_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'job_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'job_id': 'The unique identifier of the job.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-jobs#get-a-job-for-a-workflow-run'},
         {'group': 'actions',
          'name': 'download_job_logs_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/jobs/{job_id}/logs',
          'verb': 'GET',
          'summary': 'Download job logs for a workflow run',
          'route_params': ['owner', 'repo', 'job_id'],
          'required_params': ['job_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'job_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'job_id': 'The unique identifier of the job.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-jobs#download-job-logs-for-a-workflow-run'},
         {'group': 'actions',
          'name': 're_run_job_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun',
          'verb': 'POST',
          'summary': 'Re-run a job from a workflow run',
          'route_params': ['owner', 'repo', 'job_id'],
          'body_params': ['enable_debug_logging', 'enable_debugger'],
          'request_content_type': 'application/json',
          'required_params': ['job_id', 'owner', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'job_id': 'int',
                          'enable_debug_logging': 'bool',
                          'enable_debugger': 'bool'},
          'param_defaults': {'enable_debug_logging': False, 'enable_debugger': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'job_id': 'The unique identifier of the job.',
                         'enable_debug_logging': 'Whether to enable debug logging for the re-run.',
                         'enable_debugger': 'Whether to enable the debugger for the re-run of this job.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#re-run-a-job-from-a-workflow-run'},
         {'group': 'actions',
          'name': 'list_workflow_runs_for_repo',
          'path': '/repos/{owner}/{repo}/actions/runs',
          'verb': 'GET',
          'summary': 'List workflow runs for a repository',
          'route_params': ['owner', 'repo'],
          'query_params': ['head_sha', 'per_page', 'page'],
          'required_params': ['owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'per_page': 'int', 'page': 'int', 'head_sha': 'str'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'head_sha': 'Only returns workflow runs that are associated with the specified `head_sha`.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#list-workflow-runs-for-a-repository'},
         {'group': 'actions',
          'name': 'get_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}',
          'verb': 'GET',
          'summary': 'Get a workflow run',
          'route_params': ['owner', 'repo', 'run_id'],
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int'},
          'param_defaults': {},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#get-a-workflow-run'},
         {'group': 'actions',
          'name': 'list_jobs_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/jobs',
          'verb': 'GET',
          'summary': 'List jobs for a workflow run',
          'route_params': ['owner', 'repo', 'run_id'],
          'query_params': ['filter', 'per_page', 'page'],
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'run_id': 'int',
                          'filter': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'filter': 'latest', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.',
                         'filter': 'Filters jobs by their `completed_at` timestamp. `latest` returns jobs from the '
                                   'most recent execution of the workflow run. `all` returns all jobs for a workflow '
                                   'run, including from old executions of the workflow run.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run'},
         {'group': 'actions',
          'name': 'download_workflow_run_logs',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/logs',
          'verb': 'GET',
          'summary': 'Download workflow run logs',
          'route_params': ['owner', 'repo', 'run_id'],
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#download-workflow-run-logs'},
         {'group': 'actions',
          'name': 're_run_workflow',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/rerun',
          'verb': 'POST',
          'summary': 'Re-run a workflow',
          'route_params': ['owner', 'repo', 'run_id'],
          'body_params': ['enable_debug_logging'],
          'request_content_type': 'application/json',
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int', 'enable_debug_logging': 'bool'},
          'param_defaults': {'enable_debug_logging': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.',
                         'enable_debug_logging': 'Whether to enable debug logging for the re-run.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#re-run-a-workflow'},
         {'group': 'actions',
          'name': 're_run_workflow_failed_jobs',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs',
          'verb': 'POST',
          'summary': 'Re-run failed jobs from a workflow run',
          'route_params': ['owner', 'repo', 'run_id'],
          'body_params': ['enable_debug_logging'],
          'request_content_type': 'application/json',
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int', 'enable_debug_logging': 'bool'},
          'param_defaults': {'enable_debug_logging': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.',
                         'enable_debug_logging': 'Whether to enable debug logging for the re-run.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#re-run-failed-jobs-from-a-workflow-run'},
         {'group': 'checks',
          'name': 'get',
          'path': '/repos/{owner}/{repo}/check-runs/{check_run_id}',
          'verb': 'GET',
          'summary': 'Get a check run',
          'route_params': ['owner', 'repo', 'check_run_id'],
          'required_params': ['check_run_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'check_run_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'check_run_id': 'The unique identifier of the check run.'},
          'docs_url': 'https://docs.github.com/rest/checks/runs#get-a-check-run'},
         {'group': 'checks',
          'name': 'list_annotations',
          'path': '/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations',
          'verb': 'GET',
          'summary': 'List check run annotations',
          'route_params': ['owner', 'repo', 'check_run_id'],
          'query_params': ['per_page', 'page'],
          'required_params': ['check_run_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'check_run_id': 'int', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'check_run_id': 'The unique identifier of the check run.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/checks/runs#list-check-run-annotations'},
         {'group': 'pulls',
          'name': 'list_files',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/files',
          'verb': 'GET',
          'summary': 'List pull requests files',
          'route_params': ['owner', 'repo', 'pull_number'],
          'query_params': ['per_page', 'page'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#list-pull-requests-files'},
         {'group': 'pulls',
          'name': 'review_decision',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/review-decision',
          'verb': 'GET',
          'summary': 'Read the pull request review decision through Octo',
          'route_params': ['owner', 'repo', 'pull_number'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int'},
          'param_docs': {'owner': 'The account owner of the repository.',
                         'repo': 'The repository name.',
                         'pull_number': 'The number that identifies the pull request.'}}]}
