"""Selected complete entries from ghapi 2.1.5 GitHub OpenAPI metadata (Apache-2.0)."""
spec = {'base_url': 'https://api.github.com',
 'ops': [{'group': 'checks',
          'name': 'list_for_ref',
          'path': '/repos/{owner}/{repo}/commits/{ref}/check-runs',
          'verb': 'GET',
          'summary': 'List check runs for a Git reference',
          'route_params': ['owner', 'repo', 'ref'],
          'query_params': ['check_name', 'status', 'filter', 'per_page', 'page', 'app_id'],
          'required_params': ['owner', 'ref', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'ref': 'str', 'check_name': 'str', 'status': 'str', 'filter': 'str', 'per_page': 'int', 'page': 'int', 'app_id': 'int'},
          'param_defaults': {'filter': 'latest', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'ref': 'The commit reference. Can be a commit SHA, branch name (`heads/BRANCH_NAME`), or tag name (`tags/TAG_NAME`). For more information, see "[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)" in the Git documentation.',
                         'check_name': 'Returns check runs with the specified `name`.',
                         'status': 'Returns check runs with the specified `status`.',
                         'filter': 'Filters check runs by their `completed_at` timestamp. `latest` returns the most recent check runs.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/checks/runs#list-check-runs-for-a-git-reference'},
         {'group': 'repos',
          'name': 'get_combined_status_for_ref',
          'path': '/repos/{owner}/{repo}/commits/{ref}/status',
          'verb': 'GET',
          'summary': 'Get the combined status for a specific reference',
          'route_params': ['owner', 'repo', 'ref'],
          'query_params': ['per_page', 'page'],
          'required_params': ['owner', 'ref', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'ref': 'str', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'ref': 'The commit reference. Can be a commit SHA, branch name (`heads/BRANCH_NAME`), or tag name (`tags/TAG_NAME`). For more information, see "[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)" in the Git documentation.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/commits/statuses#get-the-combined-status-for-a-specific-reference'},
         {'group': 'issues',
          'name': 'list_for_repo',
          'path': '/repos/{owner}/{repo}/issues',
          'verb': 'GET',
          'summary': 'List repository issues',
          'route_params': ['owner', 'repo'],
          'query_params': ['milestone', 'state', 'assignee', 'type', 'creator', 'mentioned', 'issue_field_values', 'labels', 'sort', 'direction', 'since', 'per_page', 'page'],
          'required_params': ['owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'milestone': 'str', 'state': 'str', 'assignee': 'str', 'type': 'str', 'creator': 'str', 'mentioned': 'str', 'issue_field_values': 'str', 'labels': 'str', 'sort': 'str', 'direction': 'str', 'since': 'str', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'state': 'open', 'sort': 'created', 'direction': 'desc', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'milestone': 'If an `integer` is passed, it should refer to a milestone by its `number` field. If the string `*` is passed, issues with any milestone are accepted. If the string `none` is passed, issues without milestones are returned.',
                         'state': 'Indicates the state of the issues to return.',
                         'assignee': 'Can be the name of a user. Pass in `none` for issues with no assigned user, and `*` for issues assigned to any user.',
                         'type': 'Can be the name of an issue type. If the string `*` is passed, issues with any type are accepted. If the string `none` is passed, issues without type are returned.',
                         'creator': 'The user that created the issue.',
                         'mentioned': "A user that's mentioned in the issue.",
                         'issue_field_values': 'A comma-separated list of issue field filters in `field_slug:value` format. Only issues matching all specified field values are returned. Requires issue fields to be enabled for the repository. Issue fields are not available for user-owned repositories, and field availability for organization-owned public '
                                               "repositories depends on the organization's visibility settings. For example, `priority:Urgent,severity:High` filters issues where the `priority` field is `Urgent` AND the `severity` field is `High`.",
                         'labels': 'A list of comma separated label names. Example: `bug,ui,@high`',
                         'sort': 'What to sort results by.',
                         'direction': 'The direction to sort the results by.',
                         'since': 'Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/issues/issues#list-repository-issues'},
         {'group': 'issues',
          'name': 'get',
          'path': '/repos/{owner}/{repo}/issues/{issue_number}',
          'verb': 'GET',
          'summary': 'Get an issue',
          'route_params': ['owner', 'repo', 'issue_number'],
          'required_params': ['issue_number', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'issue_number': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'issue_number': 'The number that identifies the issue.'},
          'docs_url': 'https://docs.github.com/rest/issues/issues#get-an-issue'},
         {'group': 'pulls',
          'name': 'list',
          'path': '/repos/{owner}/{repo}/pulls',
          'verb': 'GET',
          'summary': 'List pull requests',
          'route_params': ['owner', 'repo'],
          'query_params': ['state', 'head', 'base', 'sort', 'direction', 'per_page', 'page'],
          'required_params': ['owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'state': 'str', 'head': 'str', 'base': 'str', 'sort': 'str', 'direction': 'str', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'state': 'open', 'sort': 'created', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'state': 'Either `open`, `closed`, or `all` to filter by state.',
                         'head': 'Filter pulls by head user or head organization and branch name in the format of `user:ref-name` or `organization:ref-name`. For example: `github:new-script-format` or `octocat:test-branch`.',
                         'base': 'Filter pulls by base branch name. Example: `gh-pages`.',
                         'sort': 'What to sort results by. `popularity` will sort by the number of comments. `long-running` will sort by date created and will limit the results to pull requests that have been open for more than a month and have had activity within the past month.',
                         'direction': 'The direction of the sort. Default: `desc` when sort is `created` or sort is not specified, otherwise `asc`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#list-pull-requests'},
         {'group': 'pulls',
          'name': 'create',
          'path': '/repos/{owner}/{repo}/pulls',
          'verb': 'POST',
          'summary': 'Create a pull request',
          'route_params': ['owner', 'repo'],
          'body_params': ['title', 'head', 'head_repo', 'base', 'body', 'maintainer_can_modify', 'draft', 'issue'],
          'request_content_type': 'application/json',
          'required_params': ['base', 'head', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'title': 'str', 'head': 'str', 'head_repo': 'str', 'base': 'str', 'body': 'str', 'maintainer_can_modify': 'bool', 'draft': 'bool', 'issue': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'title': 'The title of the new pull request. Required unless `issue` is specified.',
                         'head': 'The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace `head` with a user like this: `username:branch`.',
                         'head_repo': 'The name of the repository where the changes in the pull request were made. This field is required for cross-repository pull requests if both repositories are owned by the same organization.',
                         'base': 'The name of the branch you want the changes pulled into. This should be an existing branch on the current repository. You cannot submit a pull request to one repository that requests a merge to a base of another repository.',
                         'body': 'The contents of the pull request.',
                         'maintainer_can_modify': 'Indicates whether [maintainers can modify](https://docs.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) the pull request.',
                         'draft': 'Indicates whether the pull request is a draft. See "[Draft Pull Requests](https://docs.github.com/articles/about-pull-requests#draft-pull-requests)" in the GitHub Help documentation to learn more.',
                         'issue': 'An issue in the repository to convert to a pull request. The issue title, body, and comments will become the title, body, and comments on the new pull request. Required unless `title` is specified.'},
          'body_examples': {'default': {'summary': '', 'value': {'title': 'Amazing new feature', 'body': 'Please pull these awesome changes in!', 'head': 'octocat:new-feature', 'base': 'master'}}},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#create-a-pull-request'},
         {'group': 'pulls',
          'name': 'get',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}',
          'verb': 'GET',
          'summary': 'Get a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is '
                                 'not case sensitive.',
                         'pull_number': 'The number that identifies the pull request.'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#get-a-pull-request'},
         {'group': 'pulls',
          'name': 'update',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}',
          'verb': 'PATCH',
          'summary': 'Update a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'body_params': ['title', 'body', 'state', 'base', 'maintainer_can_modify'],
          'request_content_type': 'application/json',
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'title': 'str', 'body': 'str', 'state': 'str', 'base': 'str', 'maintainer_can_modify': 'bool'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'title': 'The title of the pull request.',
                         'body': 'The contents of the pull request.',
                         'state': 'State of this Pull Request. Either `open` or `closed`.',
                         'base': 'The name of the branch you want your changes pulled into. This should be an existing branch on the current repository. You cannot update the base branch on a pull request to point to another repository.',
                         'maintainer_can_modify': 'Indicates whether [maintainers can modify](https://docs.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) the pull request.'},
          'body_examples': {'default': {'summary': '', 'value': {'title': 'new title', 'body': 'updated body', 'state': 'open', 'base': 'master'}}},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#update-a-pull-request'},
         {'group': 'issues',
          'name': 'list_comments',
          'path': '/repos/{owner}/{repo}/issues/{issue_number}/comments',
          'verb': 'GET',
          'summary': 'List issue comments',
          'route_params': ['owner', 'repo', 'issue_number'],
          'query_params': ['since', 'per_page', 'page'],
          'required_params': ['issue_number', 'owner', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'issue_number': 'int',
                          'since': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'issue_number': 'The number that identifies the issue.',
                         'since': 'Only show results that were last updated after the given time. This is a timestamp '
                                  'in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: '
                                  '`YYYY-MM-DDTHH:MM:SSZ`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/issues/comments#list-issue-comments'},
         {'group': 'issues',
          'name': 'create_comment',
          'path': '/repos/{owner}/{repo}/issues/{issue_number}/comments',
          'verb': 'POST',
          'summary': 'Create an issue comment',
          'route_params': ['owner', 'repo', 'issue_number'],
          'body_params': ['body'],
          'request_content_type': 'application/json',
          'required_params': ['body', 'issue_number', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'issue_number': 'int', 'body': 'str'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'issue_number': 'The number that identifies the issue.',
                         'body': 'The contents of the comment.'},
          'body_examples': {'default': {'summary': '', 'value': {'body': 'Me too'}}},
          'docs_url': 'https://docs.github.com/rest/issues/comments#create-an-issue-comment'},
         {'group': 'pulls',
          'name': 'list_reviews',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/reviews',
          'verb': 'GET',
          'summary': 'List reviews for a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'query_params': ['per_page', 'page'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/reviews#list-reviews-for-a-pull-request'},
         {'group': 'pulls',
          'name': 'list_review_comments',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/comments',
          'verb': 'GET',
          'summary': 'List review comments on a pull request',
          'route_params': ['owner', 'repo', 'pull_number'],
          'query_params': ['sort', 'direction', 'since', 'per_page', 'page'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'pull_number': 'int',
                          'sort': 'str',
                          'direction': 'str',
                          'since': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'sort': 'created', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'sort': 'The property to sort the results by.',
                         'direction': 'The direction to sort results. Ignored without `sort` parameter.',
                         'since': 'Only show results that were last updated after the given time. This is a timestamp '
                                  'in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: '
                                  '`YYYY-MM-DDTHH:MM:SSZ`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/comments#list-review-comments-on-a-pull-request'},
         {'group': 'pulls',
          'name': 'create_reply_for_review_comment',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies',
          'verb': 'POST',
          'summary': 'Create a reply for a review comment',
          'route_params': ['owner', 'repo', 'pull_number', 'comment_id'],
          'body_params': ['body'],
          'request_content_type': 'application/json',
          'required_params': ['body', 'comment_id', 'owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'comment_id': 'int', 'body': 'str'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'comment_id': 'The unique identifier of the comment.',
                         'body': 'The text of the review comment.'},
          'body_examples': {'default': {'summary': '', 'value': {'body': 'Great stuff!'}}},
          'docs_url': 'https://docs.github.com/rest/pulls/comments#create-a-reply-for-a-review-comment'},
         {'group': 'actions',
          'name': 'get_job_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/jobs/{job_id}',
          'verb': 'GET',
          'summary': 'Get a job for a workflow run',
          'route_params': ['owner', 'repo', 'job_id'],
          'required_params': ['job_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'job_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'job_id': 'The unique identifier of the job.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-jobs#get-a-job-for-a-workflow-run'},
         {'group': 'actions',
          'name': 'download_job_logs_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/jobs/{job_id}/logs',
          'verb': 'GET',
          'summary': 'Download job logs for a workflow run',
          'route_params': ['owner', 'repo', 'job_id'],
          'required_params': ['job_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'job_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'job_id': 'The unique identifier of the job.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-jobs#download-job-logs-for-a-workflow-run'},
         {'group': 'actions',
          'name': 're_run_job_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun',
          'verb': 'POST',
          'summary': 'Re-run a job from a workflow run',
          'route_params': ['owner', 'repo', 'job_id'],
          'body_params': ['enable_debug_logging', 'enable_debugger'],
          'request_content_type': 'application/json',
          'required_params': ['job_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'job_id': 'int', 'enable_debug_logging': 'bool', 'enable_debugger': 'bool'},
          'param_defaults': {'enable_debug_logging': False, 'enable_debugger': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'job_id': 'The unique identifier of the job.',
                         'enable_debug_logging': 'Whether to enable debug logging for the re-run.',
                         'enable_debugger': 'Whether to enable the debugger for the re-run of this job.'},
          'body_examples': {'default': {'summary': '', 'value': None}},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#re-run-a-job-from-a-workflow-run'},
         {'group': 'actions',
          'name': 'list_workflow_runs_for_repo',
          'path': '/repos/{owner}/{repo}/actions/runs',
          'verb': 'GET',
          'summary': 'List workflow runs for a repository',
          'route_params': ['owner', 'repo'],
          'query_params': ['actor', 'branch', 'event', 'status', 'per_page', 'page', 'created', 'exclude_pull_requests', 'check_suite_id', 'head_sha'],
          'required_params': ['owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'actor': 'str', 'branch': 'str', 'event': 'str', 'status': 'str', 'per_page': 'int', 'page': 'int', 'created': 'str', 'exclude_pull_requests': 'bool', 'check_suite_id': 'int', 'head_sha': 'str'},
          'param_defaults': {'per_page': 30, 'page': 1, 'exclude_pull_requests': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.',
                         'actor': "Returns someone's workflow runs. Use the login for the user who created the `push` associated with the check suite or workflow run.",
                         'branch': 'Returns workflow runs associated with a branch. Use the name of the branch of the `push`.',
                         'event': 'Returns workflow run triggered by the event you specify. For example, `push`, `pull_request` or `issue`. For more information, see "[Events that trigger workflows](https://docs.github.com/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows)."',
                         'status': 'Returns workflow runs with the check run `status` or `conclusion` that you specify. For example, a conclusion can be `success` or a status can be `in_progress`. Only GitHub Actions can set a status of `waiting`, `pending`, or `requested`.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'created': 'Returns workflow runs created within the given date-time range. For more information on the syntax, see "[Understanding the search syntax](https://docs.github.com/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates)."',
                         'exclude_pull_requests': 'If `true` pull requests are omitted from the response (empty array).',
                         'check_suite_id': 'Returns workflow runs with the `check_suite_id` that you specify.',
                         'head_sha': 'Only returns workflow runs that are associated with the specified `head_sha`.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#list-workflow-runs-for-a-repository'},
         {'group': 'actions',
          'name': 'get_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}',
          'verb': 'GET',
          'summary': 'Get a workflow run',
          'route_params': ['owner', 'repo', 'run_id'],
          'query_params': ['exclude_pull_requests'],
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int', 'exclude_pull_requests': 'bool'},
          'param_defaults': {'exclude_pull_requests': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.', 'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.', 'run_id': 'The unique identifier of the workflow run.', 'exclude_pull_requests': 'If `true` pull requests are omitted from the response (empty array).'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#get-a-workflow-run'},
         {'group': 'actions',
          'name': 'list_jobs_for_workflow_run',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/jobs',
          'verb': 'GET',
          'summary': 'List jobs for a workflow run',
          'route_params': ['owner', 'repo', 'run_id'],
          'query_params': ['filter', 'per_page', 'page'],
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str',
                          'repo': 'str',
                          'run_id': 'int',
                          'filter': 'str',
                          'per_page': 'int',
                          'page': 'int'},
          'param_defaults': {'filter': 'latest', 'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.',
                         'filter': 'Filters jobs by their `completed_at` timestamp. `latest` returns jobs from the '
                                   'most recent execution of the workflow run. `all` returns all jobs for a workflow '
                                   'run, including from old executions of the workflow run.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run'},
         {'group': 'actions',
          'name': 'download_workflow_run_logs',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/logs',
          'verb': 'GET',
          'summary': 'Download workflow run logs',
          'route_params': ['owner', 'repo', 'run_id'],
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'run_id': 'The unique identifier of the workflow run.'},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#download-workflow-run-logs'},
         {'group': 'actions',
          'name': 're_run_workflow',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/rerun',
          'verb': 'POST',
          'summary': 'Re-run a workflow',
          'route_params': ['owner', 'repo', 'run_id'],
          'body_params': ['enable_debug_logging'],
          'request_content_type': 'application/json',
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int', 'enable_debug_logging': 'bool'},
          'param_defaults': {'enable_debug_logging': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.', 'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.', 'run_id': 'The unique identifier of the workflow run.', 'enable_debug_logging': 'Whether to enable debug logging for the re-run.'},
          'body_examples': {'default': {'summary': '', 'value': None}},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#re-run-a-workflow'},
         {'group': 'actions',
          'name': 're_run_workflow_failed_jobs',
          'path': '/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs',
          'verb': 'POST',
          'summary': 'Re-run failed jobs from a workflow run',
          'route_params': ['owner', 'repo', 'run_id'],
          'body_params': ['enable_debug_logging'],
          'request_content_type': 'application/json',
          'required_params': ['owner', 'repo', 'run_id'],
          'param_types': {'owner': 'str', 'repo': 'str', 'run_id': 'int', 'enable_debug_logging': 'bool'},
          'param_defaults': {'enable_debug_logging': False},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.', 'repo': 'The name of the repository without the `.git` extension. The name is not case sensitive.', 'run_id': 'The unique identifier of the workflow run.', 'enable_debug_logging': 'Whether to enable debug logging for the re-run.'},
          'body_examples': {'default': {'summary': '', 'value': None}},
          'docs_url': 'https://docs.github.com/rest/actions/workflow-runs#re-run-failed-jobs-from-a-workflow-run'},
         {'group': 'checks',
          'name': 'get',
          'path': '/repos/{owner}/{repo}/check-runs/{check_run_id}',
          'verb': 'GET',
          'summary': 'Get a check run',
          'route_params': ['owner', 'repo', 'check_run_id'],
          'required_params': ['check_run_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'check_run_id': 'int'},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'check_run_id': 'The unique identifier of the check run.'},
          'docs_url': 'https://docs.github.com/rest/checks/runs#get-a-check-run'},
         {'group': 'checks',
          'name': 'list_annotations',
          'path': '/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations',
          'verb': 'GET',
          'summary': 'List check run annotations',
          'route_params': ['owner', 'repo', 'check_run_id'],
          'query_params': ['per_page', 'page'],
          'required_params': ['check_run_id', 'owner', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'check_run_id': 'int', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'check_run_id': 'The unique identifier of the check run.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/checks/runs#list-check-run-annotations'},
         {'group': 'pulls',
          'name': 'list_files',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/files',
          'verb': 'GET',
          'summary': 'List pull requests files',
          'route_params': ['owner', 'repo', 'pull_number'],
          'query_params': ['per_page', 'page'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int', 'per_page': 'int', 'page': 'int'},
          'param_defaults': {'per_page': 30, 'page': 1},
          'param_docs': {'owner': 'The account owner of the repository. The name is not case sensitive.',
                         'repo': 'The name of the repository without the `.git` extension. The name is not case '
                                 'sensitive.',
                         'pull_number': 'The number that identifies the pull request.',
                         'per_page': 'The number of results per page (max 100). For more information, see "[Using '
                                     'pagination in the REST '
                                     'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."',
                         'page': 'The page number of the results to fetch. For more information, see "[Using '
                                 'pagination in the REST '
                                 'API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."'},
          'docs_url': 'https://docs.github.com/rest/pulls/pulls#list-pull-requests-files'},
         {'group': 'pulls',
          'name': 'review_decision',
          'path': '/repos/{owner}/{repo}/pulls/{pull_number}/review-decision',
          'verb': 'GET',
          'summary': 'Read the pull request review decision through Octo',
          'route_params': ['owner', 'repo', 'pull_number'],
          'required_params': ['owner', 'pull_number', 'repo'],
          'param_types': {'owner': 'str', 'repo': 'str', 'pull_number': 'int'},
          'param_docs': {'owner': 'The account owner of the repository.',
                         'repo': 'The repository name.',
                         'pull_number': 'The number that identifies the pull request.'}}]}
