[package]
edition.workspace = true
license.workspace = true
name = "rho-agent-host-proto"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
camino.workspace = true
clock.workspace = true
rand.workspace = true
rho-agent-types.workspace = true
rho-rpc.workspace = true
senax-encoder.workspace = true
tokio = { version = "1", features = ["io-util"] }
text.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dirs.workspace = true
tokio = { version = "1", features = ["net"] }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
tokio.workspace = true
